use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};

use super::{Message, Session, TodoItem};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoredSession {
    pub id: String,
    pub title: String,
    /// Whether `title` was generated by the AI (or explicitly renamed).
    /// Directory-name / prompt-derived titles are `false` and skipped
    /// from the input area on resume.
    #[serde(default)]
    pub title_ai_generated: bool,
    pub cwd: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub messages: Vec<Message>,
    #[serde(default)]
    pub todo_items: Vec<TodoItem>,
    #[serde(default)]
    pub provider: Option<String>,
    #[serde(default)]
    pub model: Option<String>,
    #[serde(default)]
    pub thinking: Option<String>,
    #[serde(default)]
    pub token_total: Option<u64>,
    #[serde(default)]
    pub context_window_tokens: u64,
    #[serde(default)]
    pub context_window_known: bool,
    #[serde(default)]
    pub max_output_tokens: u64,
    #[serde(default)]
    pub auto_compact: bool,
    #[serde(default)]
    pub mcp_summary: Option<String>,
    #[serde(default)]
    pub input_history: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct SessionSummary {
    pub id: String,
    pub title: String,
    pub cwd: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub last_msg_at: Option<DateTime<Utc>>,
    pub message_count: usize,
    pub token_total: Option<u64>,
}

/// Lightweight per-session metadata, stored in `meta.json` alongside
/// the heavier `session.json` (which carries the full message bodies).
/// `list()` reads only this small file so opening the session picker is
/// O(1) per session rather than deserializing every message body.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SessionMeta {
    pub id: String,
    pub title: String,
    pub title_ai_generated: bool,
    pub cwd: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub last_msg_at: Option<DateTime<Utc>>,
    pub message_count: usize,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub token_total: Option<u64>,
}

impl SessionMeta {
    fn from_stored(stored: &StoredSession) -> Self {
        SessionMeta {
            id: stored.id.clone(),
            title: stored.title.clone(),
            title_ai_generated: stored.title_ai_generated,
            cwd: stored.cwd.clone(),
            created_at: stored.created_at,
            updated_at: stored.updated_at,
            last_msg_at: stored.messages.last().map(|m| m.ts),
            message_count: stored.messages.len(),
            token_total: stored.token_total,
        }
    }
}

pub fn sessions_dir() -> Result<PathBuf> {
    Ok(crate::config::paths::config_dir()?.join("sessions"))
}

pub fn new_session_id() -> String {
    format!(
        "{}-{}",
        Utc::now().format("%Y%m%d%H%M%S%3f"),
        std::process::id()
    )
}

pub fn default_title(cwd: &Path) -> String {
    cwd.file_name()
        .and_then(|s| s.to_str())
        .filter(|s| !s.trim().is_empty())
        .unwrap_or("session")
        .to_string()
}

pub fn title_from_prompt(prompt: &str) -> String {
    const MAX_CHARS: usize = 20;
    let compact = prompt
        .lines()
        .map(str::trim)
        .find(|line| !line.is_empty())
        .unwrap_or("session")
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ");

    if compact.is_empty() {
        return "session".to_string();
    }

    let mut title: String = compact.chars().take(MAX_CHARS).collect();
    if compact.chars().count() > MAX_CHARS {
        title.push_str("...");
    }
    title
}

/// Derive a session title from the first assistant reply. Used as a
/// fallback when the AI never called `update_title` on the first turn.
/// Tries a leading `# <title>` heading (some models emit one), then a
/// `标题：`-style line, then falls back to the first non-empty line.
pub fn title_from_reply(reply: &str) -> String {
    const MAX_CHARS: usize = 20;
    for line in reply.lines().map(str::trim) {
        if line.is_empty() {
            continue;
        }
        let candidate = if let Some(rest) = line.strip_prefix('#') {
            rest.trim().trim_start_matches('#').trim()
        } else if let Some(rest) = line.strip_prefix("标题：") {
            rest.trim()
        } else if let Some(idx) = line.find("标题：") {
            line[idx + "标题：".len()..].trim()
        } else {
            line
        };
        if candidate.is_empty() {
            continue;
        }
        let mut title: String = candidate.chars().take(MAX_CHARS).collect();
        if candidate.chars().count() > MAX_CHARS {
            title.push_str("...");
        }
        return title;
    }
    "session".to_string()
}

#[derive(Debug, Clone)]
pub struct SaveMeta {
    pub provider: Option<String>,
    pub model: Option<String>,
    pub thinking: Option<String>,
    pub token_total: Option<u64>,
    pub context_window_tokens: u64,
    pub context_window_known: bool,
    pub max_output_tokens: u64,
    pub auto_compact: bool,
    pub mcp_summary: Option<String>,
    pub input_history: Vec<String>,
    /// Whether the saved title is AI/user-generated (shown in input area).
    pub title_ai_generated: bool,
}

pub fn save(id: &str, title: &str, cwd: &Path, session: &Session, meta: SaveMeta) -> Result<()> {
    let dir = sessions_dir()?;
    let session_dir = dir.join(sanitize_id(id));
    std::fs::create_dir_all(&session_dir)
        .with_context(|| format!("create {}", session_dir.display()))?;
    let path = session_dir.join("session.json");
    let now = Utc::now();
    let created_at = read_meta(&session_dir).map(|m| m.created_at).unwrap_or(now);
    let stored = StoredSession {
        id: id.to_string(),
        title: title.trim().to_string(),
        title_ai_generated: meta.title_ai_generated,
        cwd: cwd.display().to_string(),
        created_at,
        updated_at: now,
        messages: session.messages.clone(),
        todo_items: session.todo_items.clone(),
        provider: meta.provider,
        model: meta.model,
        thinking: meta.thinking,
        token_total: meta.token_total,
        context_window_tokens: meta.context_window_tokens,
        context_window_known: meta.context_window_known,
        max_output_tokens: meta.max_output_tokens,
        auto_compact: meta.auto_compact,
        mcp_summary: meta.mcp_summary,
        input_history: meta.input_history,
    };
    let raw = serde_json::to_string_pretty(&stored)?;
    std::fs::write(&path, raw).with_context(|| format!("write {}", path.display()))?;
    write_meta(&session_dir, &SessionMeta::from_stored(&stored))?;
    Ok(())
}

pub fn load(id: &str) -> Result<StoredSession> {
    let path = session_path(id)?;
    let raw = std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    serde_json::from_str(&raw).with_context(|| format!("parse {}", path.display()))
}

pub fn assets_dir(id: &str) -> Result<PathBuf> {
    Ok(sessions_dir()?.join(sanitize_id(id)).join("assets"))
}

pub fn delete(id: &str) -> Result<()> {
    let dir = sessions_dir()?.join(sanitize_id(id));
    if dir.exists() {
        std::fs::remove_dir_all(&dir).with_context(|| format!("delete {}", dir.display()))?;
    } else {
        let path = session_path(id)?;
        if path.exists() {
            std::fs::remove_file(&path).with_context(|| format!("delete {}", path.display()))?;
        }
    }
    Ok(())
}

pub fn rename(id: &str, title: &str) -> Result<()> {
    let mut stored = load(id)?;
    stored.title = title.trim().to_string();
    stored.updated_at = Utc::now();
    write_stored(&stored)
}

pub fn fork(source_id: &str, cwd: &Path, title: Option<&str>) -> Result<StoredSession> {
    let source = load(source_id)?;
    let now = Utc::now();
    let forked = StoredSession {
        id: new_session_id(),
        title: title
            .map(str::trim)
            .filter(|s| !s.is_empty())
            .map(ToOwned::to_owned)
            .unwrap_or_else(|| format!("{} (fork)", source.title)),
        title_ai_generated: source.title_ai_generated,
        cwd: cwd.display().to_string(),
        created_at: now,
        updated_at: now,
        messages: source.messages,
        todo_items: source.todo_items,
        provider: source.provider,
        model: source.model,
        thinking: source.thinking,
        token_total: source.token_total,
        context_window_tokens: source.context_window_tokens,
        context_window_known: source.context_window_known,
        max_output_tokens: source.max_output_tokens,
        auto_compact: source.auto_compact,
        mcp_summary: source.mcp_summary,
        input_history: source.input_history,
    };
    write_stored(&forked)?;
    Ok(forked)
}

pub fn list(scope_cwd: Option<&Path>) -> Result<Vec<SessionSummary>> {
    let dir = sessions_dir()?;
    if !dir.exists() {
        return Ok(Vec::new());
    }
    let scope = scope_cwd.map(|p| normalize_path_string(&p.display().to_string()));
    let mut out = Vec::new();
    for entry in std::fs::read_dir(&dir).with_context(|| format!("read {}", dir.display()))? {
        let entry = entry?;
        let session_dir = entry.path();
        if !session_dir.is_dir() {
            // Legacy flat session files may still exist
            if session_dir.extension().and_then(|s| s.to_str()) == Some("json") {
                let Some(meta) = migrate_flat_file(&session_dir) else {
                    continue;
                };
                if let Some(scope) = &scope {
                    if normalize_path_string(&meta.cwd) != *scope {
                        continue;
                    }
                }
                out.push(meta_to_summary(meta));
                continue;
            }
            continue;
        }
        let meta = match read_meta(&session_dir) {
            Some(m) => m,
            None => {
                // No meta.json yet (legacy session). Build it once from a
                // header-only scan of session.json, then persist it so
                // subsequent list() calls stay O(1).
                match migrate_dir_meta(&session_dir) {
                    Some(m) => m,
                    None => continue,
                }
            }
        };
        if let Some(scope) = &scope {
            if normalize_path_string(&meta.cwd) != *scope {
                continue;
            }
        }
        out.push(meta_to_summary(meta));
    }
    out.sort_by(|a, b| b.updated_at.cmp(&a.updated_at));
    Ok(out)
}

fn meta_to_summary(meta: SessionMeta) -> SessionSummary {
    SessionSummary {
        id: meta.id,
        title: meta.title,
        cwd: meta.cwd,
        created_at: meta.created_at,
        updated_at: meta.updated_at,
        last_msg_at: meta.last_msg_at,
        message_count: meta.message_count,
        token_total: meta.token_total,
    }
}

/// Build fresh `meta.json` for any session directory that lacks one.
/// Scans only the header of `session.json` to avoid deserializing the
/// full message bodies. Returns `None` on any read/parse failure so a
/// single corrupt session never aborts the whole list.
fn migrate_dir_meta(session_dir: &Path) -> Option<SessionMeta> {
    let path = session_dir.join("session.json");
    if !path.exists() {
        return None;
    }
    let raw = std::fs::read_to_string(&path).ok()?;
    let stored = serde_json::from_str::<StoredSession>(&raw).ok()?;
    let meta = SessionMeta::from_stored(&stored);
    write_meta(session_dir, &meta).ok()?;
    Some(meta)
}

/// Build `meta.json` for a legacy flat session file (`<id>.json` directly
/// under the sessions dir). Returns `None` on failure.
fn migrate_flat_file(path: &Path) -> Option<SessionMeta> {
    let raw = std::fs::read_to_string(path).ok()?;
    let stored = serde_json::from_str::<StoredSession>(&raw).ok()?;
    let meta = SessionMeta::from_stored(&stored);
    Some(meta)
}

/// One-time migration: scan every session directory and write a
/// `meta.json` if it is missing. Cheap to call on every `list()` (the
/// meta check is a single stat) and fully idempotent.
pub fn migrate_legacy_meta() -> Result<usize> {
    let dir = sessions_dir()?;
    if !dir.exists() {
        return Ok(0);
    }
    let mut migrated = 0;
    for entry in std::fs::read_dir(&dir)? {
        let entry = entry?;
        let session_dir = entry.path();
        if !session_dir.is_dir() {
            continue;
        }
        let meta_path = session_dir.join("meta.json");
        if meta_path.exists() {
            continue;
        }
        if migrate_dir_meta(&session_dir).is_some() {
            migrated += 1;
        }
    }
    Ok(migrated)
}

fn write_stored(stored: &StoredSession) -> Result<()> {
    let dir = sessions_dir()?;
    let session_dir = dir.join(sanitize_id(&stored.id));
    std::fs::create_dir_all(&session_dir)
        .with_context(|| format!("create {}", session_dir.display()))?;
    let path = session_dir.join("session.json");
    let raw = serde_json::to_string_pretty(stored)?;
    std::fs::write(&path, raw).with_context(|| format!("write {}", path.display()))?;
    write_meta(&session_dir, &SessionMeta::from_stored(stored))
}

fn write_meta(session_dir: &Path, meta: &SessionMeta) -> Result<()> {
    let path = session_dir.join("meta.json");
    let raw = serde_json::to_string(&meta)?;
    std::fs::write(&path, raw).with_context(|| format!("write {}", path.display()))
}

fn read_meta(session_dir: &Path) -> Option<SessionMeta> {
    let path = session_dir.join("meta.json");
    if !path.exists() {
        return None;
    }
    serde_json::from_str(&std::fs::read_to_string(path).ok()?).ok()
}

fn session_path(id: &str) -> Result<PathBuf> {
    Ok(session_path_in(&sessions_dir()?, id))
}

fn session_path_in(dir: &Path, id: &str) -> PathBuf {
    dir.join(sanitize_id(id)).join("session.json")
}

fn sanitize_id(id: &str) -> String {
    id.chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
        .collect()
}

fn normalize_path_string(s: &str) -> String {
    s.replace('\\', "/")
        .trim_end_matches('/')
        .to_ascii_lowercase()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::session::{Message, Role};

    #[test]
    fn title_from_reply_uses_markdown_heading() {
        let reply = "# 重构会话标题生成\n\n这里是对标题管理逻辑的改动说明。";
        assert_eq!(title_from_reply(reply), "重构会话标题生成");
    }

    #[test]
    fn title_from_reply_uses_title_marker() {
        let reply = "标题：修复聊天标题\n\n正文内容...";
        assert_eq!(title_from_reply(reply), "修复聊天标题");
    }

    #[test]
    fn title_from_reply_falls_back_to_first_line() {
        let reply = "我分析了标题生成的链路";
        assert_eq!(title_from_reply(reply), "我分析了标题生成的链路");
    }

    #[test]
    fn title_from_reply_truncates_long() {
        // 24 chars taken + "..." appended.
        let long = "这是一段非常非常非常非常非常非常非常非常漫长的标题文本";
        let t = title_from_reply(long);
        assert!(t.chars().count() <= 27);
        assert!(t.ends_with("..."));
    }

    #[test]
    fn title_from_reply_empty_falls_back() {
        assert_eq!(title_from_reply(""), "session");
        assert_eq!(title_from_reply("   \n\n  "), "session");
    }

    #[test]
    fn meta_round_trips_through_save_and_list() {
        // Redirect sessions_dir by overriding config path is complex for a
        // unit test; instead route through sessions_dir only when config_dir
        // is patched. We avoid touching real data by not writing to config.
        // So directly exercise the meta wire format instead.
        let stored = StoredSession {
            id: "t-1".into(),
            title: "hello".into(),
            title_ai_generated: false,
            cwd: "C:/proj".into(),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            messages: vec![Message::new(Role::User, "hi")],
            todo_items: vec![],
            provider: None,
            model: None,
            thinking: None,
            token_total: Some(42),
            context_window_tokens: 0,
            context_window_known: false,
            max_output_tokens: 0,
            auto_compact: false,
            mcp_summary: None,
            input_history: vec![],
        };
        let meta = SessionMeta::from_stored(&stored);
        assert_eq!(meta.id, "t-1");
        assert_eq!(meta.title, "hello");
        assert_eq!(meta.cwd, "C:/proj");
        assert_eq!(meta.message_count, 1);
        assert_eq!(meta.token_total, Some(42));
        assert!(meta.last_msg_at.is_some());

        // Meta serializes compactly and round-trips.
        let raw = serde_json::to_string(&meta).unwrap();
        assert!(raw.len() < 300);
        let back: SessionMeta = serde_json::from_str(&raw).unwrap();
        assert_eq!(back.id, meta.id);
        assert_eq!(back.message_count, meta.message_count);
        assert_eq!(back.last_msg_at, meta.last_msg_at);
    }

    #[test]
    fn migrate_dir_meta_writes_and_reads() {
        let dir = std::env::temp_dir().join(format!(
            "fca-migrate-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let stored = StoredSession {
            id: "m-1".into(),
            title: "legacy".into(),
            title_ai_generated: true,
            cwd: "/tmp".into(),
            created_at: Utc::now(),
            updated_at: Utc::now(),
            messages: vec![
                Message::new(Role::User, "a"),
                Message::new(Role::Assistant, "b"),
            ],
            todo_items: vec![],
            provider: None,
            model: None,
            thinking: None,
            token_total: None,
            context_window_tokens: 0,
            context_window_known: false,
            max_output_tokens: 0,
            auto_compact: false,
            mcp_summary: None,
            input_history: vec![],
        };
        std::fs::write(
            dir.join("session.json"),
            serde_json::to_string_pretty(&stored).unwrap(),
        )
        .unwrap();

        // No meta yet → migrate dir creates it.
        assert!(!dir.join("meta.json").exists());
        let meta = migrate_dir_meta(&dir).expect("migrate should succeed");
        assert_eq!(meta.id, "m-1");
        assert!(dir.join("meta.json").exists());

        // Re-run is idempotent and list() uses the meta file.
        let meta2 = migrate_dir_meta(&dir).expect("re-migrate should succeed");
        assert_eq!(meta2.id, "m-1");

        // Corrupt session.json yields None, never panics.
        std::fs::write(dir.join("session.json"), "{ not valid json").unwrap();
        assert!(migrate_dir_meta(&dir).is_none());

        std::fs::remove_dir_all(&dir).ok();
    }
}
